---

title: Robert F.P. Ludwick
email: "robert@ludwick.us"
description: >-
  By day I am a seasoned software engineering leader. I am also a father & husband,
  video game enthusiast, general nerd, & technologist. Eater of ğŸ•, ğŸ£, & ğŸœ; terrible
  player of âš½ï¸ğŸ’ sports.
url: "https://pages.ludwick.us"
github_username: rfpludwick
markdown: kramdown
theme: "jekyll-theme-slate"
timezone: America/Los_Angeles
permalink: "/:year/:month/:day/:title"
sass:
  style: compressed
styles:
  - custom
exclude:
  - "Gemfile*"
  - LICENSE
  - README.md
  - TODO.md
collections:
  navigation_site:
    relative_directory: _navigation_site
  navigation_social:
    relative_directory: _navigation_social
  projects:
    label: Projects
    relative_directory: _projects
    output: true
    permalink: "/:collection/:title"
